
logging:
 level: 
  org.springframework: INFO
  org.springframework.security: DEBUG

multitenancy:
  realms:
    - name: customer1
      issuer-uri: http://localhost:8080/realms/customer1
      jwk-set-uri: ${multitenancy.realms[0].issuer-uri}/protocol/openid-connect/certs
      resource-id: customer-1
      principal-attribute: preferred_username
    - name: customer2
      issuer-uri: http://localhost:8080/realms/customer2
      jwk-set-uri: ${multitenancy.realms[1].issuer-uri}/protocol/openid-connect/certs
      resource-id: customer-2
      principal-attribute: preferred_username
    - name: customer3
      issuer-uri: http://localhost:8080/realms/customer3
      jwk-set-uri: ${multitenancy.realms[2].issuer-uri}/protocol/openid-connect/certs
      resource-id: customer-3
      principal-attribute: preferred_username
   
server:
 port: 8081
 servlet:
  context-path: /api
