spring:
 application:
  name: springboot-keycloak-integration
 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://localhost:8080/realms/Test
     jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
 auth:
  converter:
   resource-id: mrj-app
   principal-attribute: preferred_username
   
logging:
 level:
  org.springframework.security: DEBUG
  com.mrj.keycloaksample.configuration.JwtAuthConverter: DEBUG

server:
 port: 8081
