
logging:
 level: 
  org.springframework: INFO
  org.springframework.security: DEBUG
  
spring:
 application:
  name: learning-portal-keycloak
 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://localhost:8080/realms/LearningPortal
     jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/learning
  username: postgres
  password: sillicon
 jpa: 
  properties:
   hibernate: 
    dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
    format_sql: true
  show-sql: true
  
jwt:
 auth:
  converter:
   resource-id: learning-portal
   principal-attribute: preferred_username
   
server:
 port: 8081
